platform: nodejs
platformVersion: "20"
autoDeploy: true

run:
  port: 80
  startCommand: node bin/deploy-server.js

database:
  enabled: true
  engine: postgres
  framework: raw
  sync: echo "Tables created dynamically by app from _spec.json"
  seed: node db/seed.js
